### ISSUE TITLE
Slow down caused by integration

### ISSUE THREAD

**Issue by chrisburr** [tensorprob/tensorprob#58]
I haven't had time to thoroughly test this yet however I think the integral is being evaluated for every data point in the likelihood, resulting in a significant reduction in performance.

**Comment by chrisburr** [comment]
On closer evaluation I think this may actually be caused by the change in default parameters for the minimiser #49.

**Comment by ibab** [comment]
The default parameters for the `ScipyLBFGSBOptimizer` are definitely not optimal at the moment (Pun intended).
My logic when setting them was basically "It works for a normal distributions, so it's gotta be good enough for everything else".
Shall we close this issue and open a new one for the optimizer parameters?

**Comment by chrisburr** [comment]
> My logic when setting them was basically "It works for a normal distributions, so it's gotta be good enough for everything else".

What could possibly go wrong? :laughing: 

Making a new issue for optimising the parameters of `ScipyLBFGSBOptimizer` sounds good :+1:
